name: Docs

on:
  push:
    branches: [main]
    paths: ['docs/website/**', '.github/workflows/docs.yml']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment_retry.outputs.page_url || steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: docs/website

      - name: Build docs
        run: bun run build
        working-directory: docs/website
        env:
          NODE_ENV: production
          NAKAMA_DOCS_GITHUB_PAGES: 'true'

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: docs/website/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
        continue-on-error: true

      - name: Retry Pages deploy
        if: steps.deployment.outcome == 'failure'
        id: deployment_retry
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1

      - name: Verify Pages deploy
        if: steps.deployment.outcome == 'failure' && steps.deployment_retry.outcome == 'failure'
        run: exit 1
